### ISSUE TITLE
Disagree with "...but run different clauses that match for the same function together."

### ISSUE THREAD

**Issue by indiejames** [niftyn8/elixir_style_guide#31]
This could very quickly lead to unreadable code. A function with many clauses that run together will be even less readable than a long `if then else` block in other languages.

**Comment by whatyouhide** [comment]
Could you elaborate? I'm not sure I fully understood what you mean.

**Comment by knewter** [comment]
Do you have any examples of this being a problem?  I added this one as a result of a decent bit of Elixir code and finding that it helped me mentally separate differently-named functions (I would argue that different-arity functions should be 'separated' more as well, not sure if that's clear).  Anyway, if you have any examples of a function that causes this grief, could you share them?  I don't want to encourage someone to do something that leads to unreadable code, but in my experience this did the opposite.  One data point isn't enough though.

**Comment by indiejames** [comment]
I just think it is useful to consider each clause as a standalone function that can be viewed, reasoned about, and tested in isolation. Being able to break down a complex function into parts like this is a strength of Elixir. Certainly it makes sense to group them together in a file, but with no newline separation at all it seems like they just become one giant function, which I find more difficult to reason about.

```
def some_function([]) do
  :ok
end
def some_function([first|rest]) when something do
  some_function(rest)
end
def some_function([first|rest]) when something_different do
  some_function(rest)
  |> foo(first)
end
def some_function([first|rest]) when something_else do
  some_other_function(rest)
end
def some_function(first|rest]) when something_else_again do
  some_other_function2(reset)
end
def some_function([first|rest]) when yada_yada do
  some_other_function3(rest)
end
```

A few more clauses and it begins to blend together to me. And these are one or two line bodies. Slightly longer bodies would seem to lead to a big mess.

I am a total Elixir newbie, however, so there is that. Also, I see that this seems to be the [erlang way](http://learnyousomeerlang.com/syntax-in-functions) of doing this as well, so maybe I'm in the  wrong here. 

I would feel more comfortable if this were suggested for functions with a few simple clauses, and not for all functions with multiple clauses. Sort of like the distinction between using one line function definition for short functions and multiline definitions for longer functions.

**Comment by Gazler** [comment]
This should have been closed by https://github.com/niftyn8/elixir_style_guide/pull/39 unless I am missing something?

**Comment by niftyn8** [comment]
Yup. Thanks!
