### ISSUE TITLE
Indentation on pipelines that bind a variable

### ISSUE THREAD

**Issue by jordan0day** [niftyn8/elixir_style_guide#32]
In the current style guide, the only real commentary on pipelines is:

```Elixir
# Multiline pipelines use a single level of indentation.
some_string
|> String.downcase
|> String.strip
```

(sidenote: "single level of indentation" here seems to imply *no* indentation, unless I'm missing something?)

But what about when the result of that pipelining should be bound to a variable? Like

```Elixir
result = some_string
|> String.downcase
|> String.strip
```

I've found myself indenting the pipelines by two spaces to give a little bit of clarity, like so:

```Elixir
result = some_string
  |> String.downcase
  |> String.strip
```

but I'm curious if anyone else has a take on this? Or is binding the result of a pipeline frowned upon for some reason?

**Comment by alxndr** [comment]
The [plugin for vim](https://github.com/elixir-lang/vim-elixir) indents to the root level of the thing being piped in:

    result = some_string
             |> String.downcase
             |> String.strip

**Comment by knewter** [comment]
I also do that manually (need to update my elixir.vim, is ooooold)

On Tue, Feb 3, 2015 at 2:17 PM, Alexander Quine <notifications@github.com>
wrote:

> The plugin for vim <https://github.com/elixir-lang/vim-elixir> indents to
> the root level of the thing being piped in:
>
> result = some_string
>          |> String.downcase
>          |> String.strip
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/niftyn8/elixir_style_guide/issues/32#issuecomment-72725806>
> .
>



-- 
*Josh Adams*
CTO | isotope|eleven <http://www.isotope11.com>
[cell] (205) 215-3957
[work] (877) 476-8671 x201

**Comment by asaaki** [comment]
If I come across to bind the value of a pipeline I tend to extract the pipeline into its own function and then indent the pipes one level. But that's just a matter of taste.

```elixir
def foo do
  result = pipestuff
  # ...
end

defp pipestuff do
  initial_value
    |> step_one
    |> step_two
end
```

Even if you don't indent (the pipes) at all the extraction into separate functions seems to be preferrable IMHO.

**Comment by niftyn8** [comment]
Anyone feel free to just open a PR updating the document. At the time it was written there was very little style to go on yet.
