### ISSUE TITLE
Convention for naming a private method

### ISSUE THREAD

**Issue by tacticiankerala** [niftyn8/elixir_style_guide#42]
I was wondering how to name a private method especially in a situation where it has the exact same intention but accepts some additional parameters(e.g.: accumulator)?

For example:
```elixir
defmodule Factors do
  def factors n do
    _factors HashSet.new, n, n
  end

  defp _factors set, _, 0 do
    set
  end
  defp _factors set, n, x do
    if rem(n, x) == 0 do
      _factors HashSet.put(set, x), n, (x-1)
    else
      _factors set, n, (x-1)
    end
  end
end
```

**Comment by knewter** [comment]
I always either name it the same (if it's a different arity from the existing public one) or name it `do_factors`

**Comment by tacticiankerala** [comment]
Thanks @knewter ! I think I will stick to the 'same name if parity is different' rule for now.
