### ISSUE TITLE
Challenge single level of indentation for multiline pipes

### ISSUE THREAD

**Issue by bcardarella** [niftyn8/elixir_style_guide#43]
I'd like to challenge this:

```elixir
# Multiline pipelines use a single level of indentation.
some_string
|> String.downcase
|> String.strip
```

with:

```elixir
# Multiline pipelines should be indented.
some_string
  |> String.downcase
  |> String.strip
```

I realize that the first version is something that has been used pretty much everywhere but I believe it is misleading to the eye. Indentation implies a relationship to the outdented value, not indenting could imply there is no relationship.

Thoughts?

**Comment by wyaeld** [comment]
I tend to agree that indenting implies a connection and is easier to eyeball

**Comment by Gazler** [comment]
Just quoting the relevant part as it currently stands for ease:

```elixir
# Multiline pipelines use a single level of indentation.
some_string
|> String.downcase
|> String.strip

# Multiline pipelines on the right side of a pattern match
# should be indented on a newline
sanitized_string =
  some_string
  |> String.downcase
  |> String.strip
```

How would this proposal looks with  binding as it stands?

```elixir
sanitized_string = 
  some_string
    |> String.downcase
   |> String.strip
```

Personally I disagree with the proposal, however it could just be that I am so used to doing without indentation.

**Comment by chrismccord** [comment]
You can and should be free to write code exactly how you've laid out. But if we must bikeshed, I Iike mine blue. Here's why: the current standard that multiline pipelines use a single level of indentation is preferred because the `|> ` already denotes visual indentation to my eye.

**Comment by bcardarella** [comment]
@Gazler I've written bindings in the 2nd form

**Comment by alxndr** [comment]
Agree with @chrismccord — the `|>` serves as indentation to my eyes.

**Comment by whatyouhide** [comment]
Came here to write exactly what @chrismccord wrote. Think about how IEx visually shows stuff when that stuff is part of a single expression:

```
iex> 1 +
...> 2
```

Showing the different prompt (`...>`) makes it clear that that expression is unfinished. I see a leading `|>` as an "unfinished expression" prompt.

**Comment by knewter** [comment]
Agree that I view this pipe as an indentation already

**Comment by niftyn8** [comment]
Since this has been debated a couple times before and a lot of people seem to come out on the side of seeing `|>` as indention, anyone have any objections to closing this? (Will give a day or so for people to respond)

**Comment by adamkittelson** [comment]
Hopping on the no-need-to-indent bandwagon.

However I do tend to do:
````
some_var = some_value
           |> transformed
           |> by
           |> some
           |> pipes
````

rather than:
````
some_var = 
  some_value
  |> transformed
  |> by
  |> some
  |> pipes
````

**Comment by whatyouhide** [comment]
@adamkittelson this was discussed at length in #33 and the second version was pretty much a consensus.

**Comment by asaaki** [comment]
Regarding the "the pipe operator acts as indentation already":
I guess it depends sometimes more on the used color scheme for the syntax highlighting. In some of them the operator is even more outstanding (sometimes more than the following code), so it doesn't help to see an indentation at all. (Like seen above in the GH snippets.)
Without any colors it is equal to all typed stuff and the eye can't jump again, too.
So, please, don't be so quick stating it as a kind of fact; some people see differently than you do.

But in the end I just agree with @chrismccord 's first part of his answer:

> You can and should be free to write code exactly how you've laid out.

**Comment by adamkittelson** [comment]
@whatyouhide I don't mind it if the variable name is long, or if i'm deeply nested or otherwise edging toward the right margin, but I think it looks silly do do it that way if you've got the space to do it the other way.

I guess in other words I like Jose's wording in that thread "If the right side of = goes too far (either because the left side is long or the right one is), I break it into another line"

If it's too long do it that way, but if I'm not space constrained I'm going to default to not having the hanging `=`

**Comment by ericmj** [comment]
One more vote for single level of indentation. The `|>` already provides enough guideline.

**Comment by likethesky** [comment]
@niftyn8 I think they've had a day (or 112!) to respond, so I vote to finally close this. For the record, I'm in agreement with most here that the first unindented `|>` does provide a visual clue that it's connected to the (initial) expression above it, even though in general I tend to prefer more whitespace.

Btw, `|>` is the `pipe operator` **not** the `pipeline operator`. However, once used, a pipe operator in combination with the operands does seem to constitute a pipeline.  :bowtie:  At least, that's the usage I see in the docs. Hence, "a multiline pipeline, or multiline pipelines" would be correct, but we "use many pipe operators in a multiline (or single line, for that matter) pipeline." However, I suspect my pedantry fights a losing battle over this distinction!
