### ISSUE TITLE
Add suggestion of :default in cond default case

### ISSUE THREAD

**Issue by miwee** [niftyn8/elixir_style_guide#45]
In the section, "An atom can be used as a catch-all expression in a cond as it evaluates to a truthy value. Suggested atoms are :else or :otherwise"

suggestion of :default can also be added.

default is also the catchall condition in C switch statements, and should be familiar.

**Comment by ericmj** [comment]
The convention is to use `true` as seen in the docs: http://elixir-lang.org/docs/master/elixir/Kernel.SpecialForms.html#cond/1

**Comment by whatyouhide** [comment]
Can this be closed? We're suggesting to use `true` with `:else` as an alternative now, so I guess we're good here.
