### ISSUE TITLE
Ambiguity about parens in pipelines

### ISSUE THREAD

**Issue by joeyAghion** [niftyn8/elixir_style_guide#50]
The style guide states:

* Use parentheses when you have arguments, no parentheses when you don't.

Later, it states:

* Use parentheses in function calls, especially inside a pipeline.

```elixir
# preferred
f(3) |> g()
```

I'm unclear about whether the parens in `g()` are intentional (I don't believe there's any parsing ambiguity). If they're intentional, I suggest revising the language to say `Use parentheses in function calls within a pipeline, even without arguments`. However, if that's just an oversight the example should be `f(3) |> g`.

I'm happy to PR the change if someone can clarify the intent.

**Comment by ericmj** [comment]
The parenthesis is not necessary when piping nullary functions. It can be used to clarify for the programmer if calling a function or referencing a variable, but in the case of piping it is clear that a function is called - since you cannot pipe into a variable.
