### ISSUE TITLE
Multiline pipe wording ambiguity?

### ISSUE THREAD

**Issue by jimm** [niftyn8/elixir_style_guide#65]
"# Multiline pipelines use a single level of indentation." but the pipe is not indented further than the previous line. Would "Multiline pipelines do not change indentation" or "Multiline pipelines do not indent further" be clearer, perhaps?

```elixir
# Multiline pipelines do not change indentation
foo
|> do_something
|> do_something_else
```

**Comment by kholbekj** [comment]
This actually confused me, also, I think your reads much better. I took the liberty of a slight rewording, do tell if you disagree.

**Comment by jimm** [comment]
Perfect! Thank you, @kholbekj.

**Comment by eksperimental** [comment]
@niftyn8 please close this one.

**Comment by jimm** [comment]
Closing; improved wording was merged. Thank you.
