### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by victorlcampos** [niftyn8/elixir_style_guide#73]
Hi,
It would be nice with it's possible translate this guide. I'm member from phoenixframework-Brazil. We are translating the phoenix guide and we can help translate this style guide for portuguese.

**Comment by dayvsonlima** [comment]
+1

**Comment by niftyn8** [comment]
@victorlcampos That'd be lovely. What kind of support do you need from folks already contributing to this?

**Comment by eksperimental** [comment]
:+1: 
any updates on this one? If not, we should add a new section and include the translated guide.
if not, i think we could close this issue
/cc @niftyn8

**Comment by victorlcampos** [comment]
Sorry @eksperimental,
I did not have time to look with this, I stoped work with Elixir for now.

When I start again I reopen this issue.
